/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SWExGaLgFlj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <Package2Icon className="w-6 h-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <Link className="font-bold" href="#">
            Orders
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Products
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Analytics
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search products..."
                type="search"
              />
            </div>
          </form>
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="flex flex-col gap-4">
          <div className="grid w-full gap-2 md:grid-cols-2 lg:grid-cols-4">
            <Card className="flex flex-col items-start p-4 md:p-6">
              <div className="flex flex-row items-center gap-4">
                <BedIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
                <div className="grid gap-0.5">
                  <CardTitle className="text-base font-bold">Bed 101</CardTitle>
                  <CardDescription className="text-sm">Patient: John Doe</CardDescription>
                </div>
                <AlertTriangleIcon className="ml-auto w-4 h-4 text-red-500 dark:text-red-400" />
              </div>
            </Card>
            <Card className="flex flex-col items-start p-4 md:p-6">
              <div className="flex flex-row items-center gap-4">
                <BedIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
                <div className="grid gap-0.5">
                  <CardTitle className="text-base font-bold">Bed 102</CardTitle>
                  <CardDescription className="text-sm">Patient: Alice Johnson</CardDescription>
                </div>
                <CheckCircleIcon className="ml-auto w-4 h-4 text-green-500 dark:text-green-400" />
              </div>
            </Card>
            <Card className="flex flex-col items-start p-4 md:p-6">
              <div className="flex flex-row items-center gap-4">
                <BedIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
                <div className="grid gap-0.5">
                  <CardTitle className="text-base font-bold">Bed 103</CardTitle>
                  <CardDescription className="text-sm">Patient: Emily Smith</CardDescription>
                </div>
                <CheckCircleIcon className="ml-auto w-4 h-4 text-green-500 dark:text-green-400" />
              </div>
            </Card>
            <Card className="flex flex-col items-start p-4 md:p-6">
              <div className="flex flex-row items-center gap-4">
                <BedIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
                <div className="grid gap-0.5">
                  <CardTitle className="text-base font-bold">Bed 104</CardTitle>
                  <CardDescription className="text-sm">Patient: David Brown</CardDescription>
                </div>
                <AlertTriangleIcon className="ml-auto w-4 h-4 text-red-500 dark:text-red-400" />
              </div>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}

function AlertTriangleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </svg>
  )
}


function BedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 4v16" />
      <path d="M2 8h18a2 2 0 0 1 2 2v10" />
      <path d="M2 17h20" />
      <path d="M6 8v9" />
    </svg>
  )
}


function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
