/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dbFsmJPvsaR
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Judson } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="w-full py-6 space-y-6 md:py-12">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Symptom To Disease AI ChatBot</h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Enter your symptoms below to get a preliminary idea of possible conditions. This chatbot is for general
                purposes only. Always consult a healthcare professional for a proper diagnosis.
              </p>
            </div>
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row">
            <Button size="lg" variant="outline">
              Contact Sales
            </Button>
          </div>
        </div>
      </div>
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="grid gap-4">
            <div className="flex items-center space-x-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="bg-gray-100 rounded-xl flex-1 p-4 text-sm dark:bg-gray-800">
                Hi there! I'm the Symptom To Disease AI ChatBot. I'm here to help you understand your symptoms. Please
                enter your symptoms below, and I'll provide you with some potential conditions. Remember, this is just a
                preliminary assessment. For a proper diagnosis, make sure to consult a healthcare professional.
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <div className="flex-1" />
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="bg-gray-100 rounded-xl p-4 text-sm dark:bg-gray-800">
                I'm sorry, I'm not equipped to handle that request. If you have any other symptoms or questions, feel
                free to ask!
              </div>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center space-x-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="bg-gray-100 rounded-xl p-4 text-sm dark:bg-gray-800">Coughing and fever</div>
            </div>
            <div className="flex items-center space-x-4">
              <div className="flex-1" />
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="bg-gray-100 rounded-xl p-4 text-sm dark:bg-gray-800">
                Based on your symptoms, you may be experiencing a respiratory infection. However, this is not a
                diagnosis. Please consult a healthcare professional for proper advice.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
